name: upload file test
on:
  workflow_dispatch:

jobs:
  upload-file:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: mkdir dir
        run:
          mkdir -p ./path

      - name: echo hello
        run:
          echo hello > ./path/hello.txt

      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: "hello.txt"
          path: "./path/hello.txt"
