name: upload file test
on:
  workflow_dispatch:

jobs:
  upload-file:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: mkdir dir
        run:
          mkdir -p ./path/files/

      - name: input to file
        run:
          echo "hello" > ./path/files/hello.txt;
          echo "world" > ./path/files/world.txt;

      - name: upload files directory
        uses: actions/upload-artifact@v2
        with:
          name: "files"
          path: "./path"

      - name: download dir
        uses: actions/download-artifact@v2
        with:
          name: "upload files directory"

      - name: output
        run:
          echo $(<./path/files/hello.txt)

